apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana
    env:
      - name: GF_SECURITY_ADMIN_PASSWORD
        value: "admin123"
    ports:
    - containerPort: 3000
